server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    additional-tld-skip-patterns: "*.jar"


spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: true
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: /resources/

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopping?serverTimezone=Asia/Seoul
    username: uk
    password: mambas24@@


  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false